name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [1.15, 1.16, 1.17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - run: go build
      - run: go test